-- FRIDAY Supabase Free-Tier — Initial Schema
-- Migration: 001_initial_schema.sql
-- Apply via: Supabase SQL Editor or `npx supabase db push`
-- DO NOT edit this file after it has been applied. Create a new migration instead.

-- ─── conversations ────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS conversations (
  id           TEXT PRIMARY KEY,
  title        TEXT NOT NULL DEFAULT 'New conversation',
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  metadata     JSONB
);

-- ─── messages ─────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS messages (
  id               TEXT PRIMARY KEY,
  conversation_id  TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  role             TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
  content          TEXT NOT NULL,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  metadata         JSONB
);

-- ─── tasks ────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS tasks (
  id               TEXT PRIMARY KEY,
  conversation_id  TEXT REFERENCES conversations(id) ON DELETE SET NULL,
  goal             TEXT NOT NULL,
  status           TEXT NOT NULL DEFAULT 'planning',
  started_at       TIMESTAMPTZ,
  completed_at     TIMESTAMPTZ,
  error_code       TEXT,
  error_message    TEXT,
  metadata         JSONB
);

-- ─── task_actions ─────────────────────────────────────────────────────────────
-- Stores compact audit records only. No screenshots, no full DOM, no large payloads.

CREATE TABLE IF NOT EXISTS task_actions (
  id                    TEXT PRIMARY KEY,
  task_id               TEXT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  action_id             TEXT NOT NULL,
  action_type           TEXT NOT NULL,
  status                TEXT NOT NULL DEFAULT 'running',
  risk                  TEXT,
  requires_confirmation BOOLEAN,
  confirmed             BOOLEAN,
  started_at            TIMESTAMPTZ,
  completed_at          TIMESTAMPTZ,
  result_summary        TEXT,
  error_code            TEXT,
  metadata              JSONB
);

-- ─── memories ─────────────────────────────────────────────────────────────────
-- Only intentionally promoted long-term memories. NOT automatic conversation copies.

CREATE TABLE IF NOT EXISTS memories (
  id          TEXT PRIMARY KEY,
  content     TEXT NOT NULL,
  category    TEXT,
  importance  SMALLINT DEFAULT 50 CHECK (importance >= 0 AND importance <= 100),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  metadata    JSONB
);

-- ─── preferences ──────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS preferences (
  id          TEXT PRIMARY KEY,
  key         TEXT UNIQUE NOT NULL,
  value       JSONB,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ─── model_status ─────────────────────────────────────────────────────────────
-- Safe public metadata only. API keys are NEVER stored here.

CREATE TABLE IF NOT EXISTS model_status (
  id                  TEXT PRIMARY KEY,
  role                TEXT UNIQUE NOT NULL,
  model_id            TEXT NOT NULL,
  provider            TEXT,
  free                BOOLEAN NOT NULL DEFAULT true,
  available           BOOLEAN NOT NULL DEFAULT true,
  healthy             BOOLEAN NOT NULL DEFAULT true,
  verification_status TEXT,
  verified_at         TIMESTAMPTZ,
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);
